<a href="https://colab.research.google.com/github/alizauzmasyed/AlizaUzma-25BAI0197/blob/main/EDA_EXP_4.2_28.07.2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer

df = pd.DataFrame({
    "Age": [25, np.nan, 30, 45, 22],
    "Salary": [50000, 60000, np.nan, 80000, 45000],
    "Category": ["A", "B", "A", np.nan, "B"],
})
print(df)

    Age   Salary Category
0  25.0  50000.0        A
1   NaN  60000.0        B
2  30.0      NaN        A
3  45.0  80000.0      NaN
4  22.0  45000.0        B

In [7]:
mean_imputer = SimpleImputer(strategy="mean")
df["Age_Mean"] = mean_imputer.fit_transform(df[["Age"]])
df

    Age   Salary Category  Age_Mean
0  25.0  50000.0        A      25.0
1   NaN  60000.0        B      30.5
2  30.0      NaN        A      30.0
3  45.0  80000.0      NaN      45.0
4  22.0  45000.0        B      22.0

In [8]:
median_imputer = SimpleImputer(strategy="median")
df["Salary_Median"] = median_imputer.fit_transform(df[["Salary"]])
df

    Age   Salary Category  Age_Mean  Salary_Median
0  25.0  50000.0        A      25.0        50000.0
1   NaN  60000.0        B      30.5        60000.0
2  30.0      NaN        A      30.0        55000.0
3  45.0  80000.0      NaN      45.0        80000.0
4  22.0  45000.0        B      22.0        45000.0

In [9]:
mode_imputer = SimpleImputer(strategy="most_frequent")
df["Category_Mode"] = mode_imputer.fit_transform(df[["Category"]]).ravel()
df

    Age   Salary Category  Age_Mean  Salary_Median Category_Mode
0  25.0  50000.0        A      25.0        50000.0             A
1   NaN  60000.0        B      30.5        60000.0             B
2  30.0      NaN        A      30.0        55000.0             A
3  45.0  80000.0      NaN      45.0        80000.0             A
4  22.0  45000.0        B      22.0        45000.0             B

In [10]:
num_cols = ["Age", "Salary"]
mice_imputer = IterativeImputer(max_iter=10, random_state=42)
df_mice = df[num_cols].copy()
df_mice.iloc[:, :] = mice_imputer.fit_transform(df_mice)
df["Age_MICE"] = df_mice["Age"]
df["Salary_MICE"] = df_mice["Salary"]
display(df)

,Age,Salary,Category,Age_Mean,Salary_Median,Category_Mode,Age_MICE,Salary_MICE
0,25.0,50000.0,A,25.0,50000.0,A,25.000000,50000.000000
1,NaN,60000.0,B,30.5,60000.0,B,31.766487,60000.000000
2,30.0,NaN,A,30.0,55000.0,A,30.000000,57324.583367
3,45.0,80000.0,NaN,45.0,80000.0,A,45.000000,80000.000000
4,22.0,45000.0,B,22.0,45000.0,B,22.000000,45000.000000