In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
Dataset = {
    'Employee ID': np.arange(1, 21),
    'Name': [f'Employee_{i}' for i in range(1, 21)],
    'Department': np.random.choice(['HR', 'Engineering', 'Marketing', 'Sales', 'Finance'], 20),
    'Age': np.random.randint(22, 60, 20),
    'Salary': np.random.randint(40000, 120000, 20)
}
df = pd.DataFrame(Dataset)
df

    Employee ID         Name   Department  Age  Salary
0             1   Employee_1    Marketing   31   91711
1             2   Employee_2  Engineering   51   51744
2             3   Employee_3           HR   45   45944
3             4   Employee_4    Marketing   45   91508
4             5   Employee_5        Sales   30   67883
5             6   Employee_6           HR   22   42237
6             7   Employee_7      Finance   48   93653
7             8   Employee_8  Engineering   42  106199
8             9   Employee_9           HR   43   60581
9            10  Employee_10           HR   33  113283
10           11  Employee_11  Engineering   51  111787
11           12  Employee_12  Engineering   54   90260
12           13  Employee_13    Marketing   48   45383
13           14  Employee_14           HR   45   87768
14           15  Employee_15    Marketing   57   50552
15           16  Employee_16  Engineering   46   64732
16           17  Employee_17  Engineering   46   73559
17           18  Employee_18  Engineering   41   73333
18           19  Employee_19  Engineering   34   47093
19           20  Employee_20      Finance   26   57403

In [2]:
df.head()

   Employee ID        Name   Department  Age  Salary
0            1  Employee_1    Marketing   31   91711
1            2  Employee_2  Engineering   51   51744
2            3  Employee_3           HR   45   45944
3            4  Employee_4    Marketing   45   91508
4            5  Employee_5        Sales   30   67883

In [3]:
df.tail()

    Employee ID         Name   Department  Age  Salary
15           16  Employee_16  Engineering   46   64732
16           17  Employee_17  Engineering   46   73559
17           18  Employee_18  Engineering   41   73333
18           19  Employee_19  Engineering   34   47093
19           20  Employee_20      Finance   26   57403

In [4]:
display(df.columns.tolist())

['Employee ID', 'Name', 'Department', 'Age', 'Salary']

In [5]:
display(df.dtypes)

Employee ID     int64
Name           object
Department     object
Age             int64
Salary          int64
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee ID  20 non-null     int64
 1   Name         20 non-null     object
 2   Department   20 non-null     object
 3   Age          20 non-null     int64
 4   Salary       20 non-null     int64
dtypes: int64(3), object(2)
memory usage: 932.0+ bytes

In [7]:
df.describe()

       Employee ID        Age         Salary
count     20.00000  20.000000      20.000000
mean      10.50000  41.900000   73330.650000
std        5.91608   9.541599   23421.525889
min        1.00000  22.000000   42237.000000
25%        5.75000  33.750000   51446.000000
50%       10.50000  45.000000   70608.000000
75%       15.25000  48.000000   91558.750000
max       20.00000  57.000000  113283.000000

In [8]:
df.isnull().sum()

Employee ID    0
Name           0
Department     0
Age            0
Salary         0
dtype: int64

In [9]:
(df.isnull().sum() / len(df)) * 100

Employee ID    0.0
Name           0.0
Department     0.0
Age            0.0
Salary         0.0
dtype: float64