In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv('/content/SuicideChina.csv')

In [45]:
df.value_counts()

rownames  Person_ID  Hospitalised  Died  Urban    Year  Month  Sex     Age  Education  Occupation  method
2571      2571       yes           no    unknown  2010  7      female  44   primary    farming     Pesticide       1
1         1          yes           no    no       2010  12     female  39   Secondary  household   Other poison    1
2         2          no            yes   no       2009  3      male    83   primary    farming     Hanging         1
3         3          no            yes   no       2010  2      male    60   primary    farming     Hanging         1
4         4          no            yes   no       2011  1      male    73   primary    farming     Hanging         1
                                                                                                                  ..
16        16         yes           no    no       2009  2      female  56   primary    farming     Pesticide       1
15        15         no            yes   no       2010  12     male    65   Secondary  farming     Pesticide       1
14        14         no            yes   no       2011  1      female  42   primary    farming     Cutting         1
13        13         no            yes   no       2010  6      female  79   iliterate  farming     Hanging         1
12        12         no            yes   no       2010  3      female  77   iliterate  farming     Hanging         1
Name: count, Length: 2571, dtype: int64

In [46]:
df.keys()

Index(['rownames', 'Person_ID', 'Hospitalised', 'Died', 'Urban', 'Year',
       'Month', 'Sex', 'Age', 'Education', 'Occupation', 'method'],
      dtype='object')

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2571 entries, 0 to 2570
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   rownames      2571 non-null   int64
 1   Person_ID     2571 non-null   int64
 2   Hospitalised  2571 non-null   object
 3   Died          2571 non-null   object
 4   Urban         2571 non-null   object
 5   Year          2571 non-null   int64
 6   Month         2571 non-null   int64
 7   Sex           2571 non-null   object
 8   Age           2571 non-null   int64
 9   Education     2571 non-null   object
 10  Occupation    2571 non-null   object
 11  method        2571 non-null   object
dtypes: int64(5), object(7)
memory usage: 241.2+ KB

In [48]:
df.count()

rownames        2571
Person_ID       2571
Hospitalised    2571
Died            2571
Urban           2571
Year            2571
Month           2571
Sex             2571
Age             2571
Education       2571
Occupation      2571
method          2571
dtype: int64

In [50]:
df.sort_values(by='Year')

,rownames,Person_ID,Hospitalised,Died,Urban,Year,Month,Sex,Age,Education,Occupation,method
763,764,764,no,yes,no,2009,6,male,81,iliterate,farming,Other poison
762,763,763,yes,no,no,2009,7,female,42,Secondary,farming,Pesticide
761,762,762,no,yes,no,2009,4,male,64,Secondary,farming,Pesticide
760,761,761,yes,no,no,2009,6,female,50,Secondary,farming,Pesticide
758,759,759,yes,yes,no,2009,6,female,23,Secondary,farming,Pesticide
...,...,...,...,...,...,...,...,...,...,...,...,...
29,30,30,yes,no,no,2011,4,female,76,primary,farming,Poison unspec
26,27,27,no,yes,no,2011,8,female,59,primary,farming,Pesticide
25,26,26,no,yes,no,2011,7,male,80,primary,farming,Hanging
9,10,10,yes,no,no,2011,1,female,30,Secondary,others/unknown,Poison unspec
3,4,4,no,yes,no,2011,1,male,73,primary,farming,Hanging

In [51]:
df.isnull()

,rownames,Person_ID,Hospitalised,Died,Urban,Year,Month,Sex,Age,Education,Occupation,method
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
2566,False,False,False,False,False,False,False,False,False,False,False,False
2567,False,False,False,False,False,False,False,False,False,False,False,False
2568,False,False,False,False,False,False,False,False,False,False,False,False
2569,False,False,False,False,False,False,False,False,False,False,False,False
2570,False,False,False,False,False,False,False,False,False,False,False,False

In [52]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2566    False
2567    False
2568    False
2569    False
2570    False
Length: 2571, dtype: bool